#define PRODUCT_NAME			"TAP_Windows"
#define PRODUCT_VERSION			"9.22.1"
#define PRODUCT_VERSION_RESOURCE	9,0,0,22
#define PRODUCT_TAP_WIN_COMPONENT_ID	"tap0901"
#define PRODUCT_TAP_WIN_MAJOR		9
#define PRODUCT_TAP_WIN_MINOR		22
#define PRODUCT_TAP_WIN_PROVIDER		"TAP-Windows Provider V9"
#define PRODUCT_TAP_WIN_DEVICE_DESCRIPTION	"TAP-Windows Adapter V9"
#define PRODUCT_TAP_WIN_RELDATE		"11/05/2014"
#define PRODUCT_TAP_WIN_CHARACTERISTICS	0x81
